#!/bin/bash
readarray history < cat ~/.bash_history 

for command in "${history[@]}"
do
   : 
   readarray 
	for bssid in "${bssids[@]}"
	do
		: 
	echo "cracking"+$bssid+" with wordlist"+$list
	aircrack-ng -w $WORDLISTS$list -b $bssid -q -l $bssid wpa.cap
	done
done
