#!/bin/bash

iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 22 -j REDIRECT --to-ports 22
iptables -t nat -A PREROUTING -i eth0 -p udp --dport 53 -j REDIRECT --to-ports 53

iptables -t nat -A PREROUTING -i eth0 -d betcoin.ag -p tcp --syn -j REDIRECT --to-ports 9040
