#!/bin/bash

echo "hello, root!"
echo " taking down wlan1"
ifconfig wlan0 down
sleep 3

echo "setting Region to Bolivia"
iw reg set BO
sleep 3

echo "setting TxPower to 30"
iwconfig wlan0 txpower 30
sleep 2

echo "starting wlan1"
ifconfig wlan0 up
echo "pulling wlan1 interface up"
iwconfig
sleep 5

echo "good bye"
